apiVersion: v1
kind: Service
metadata:
  name: {{ include "dicebear-shim.fullname" . }}-dicebear
  labels:
    {{- include "dicebear-shim.labels" . | nindent 4 }}
    app.kubernetes.io/component: dicebear
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.dicebear.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dicebear-shim.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dicebear
